# -----------------------------------------------------------------------------
# Kanagawa Paper Canvas
# Upstream: https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml
# URL: https://wezterm.org/config/appearance.html
# -----------------------------------------------------------------------------

[colors]
foreground = "#54546b"
background = "#e1e1de"
cursor_bg = "#618bb6"
cursor_border = "#618bb6"
cursor_fg = "#e1e1de"
selection_bg = "#c4cbdc"
selection_fg = "#858479"
split = "#c4cbdc"
compose_cursor = "#5f8a9b"
scrollbar_thumb = "#a9a8a0"

ansi = [
  "#3e3e5a",
  "#ba4e5a",
  "#738859",
  "#a67337",
  "#526994",
  "#a85b76",
  "#597b75",
  "#54546b"
]
brights = [
  "#54546b",
  "#c95556",
  "#709062",
  "#c08a48",
  "#618bb6",
  "#7967a2",
  "#5f847c",
  "#444466"
]

[colors.indexed]
16 = "#b8805e"
17 = "#ba4e5a"

[colors.tab_bar]
background = "#cbc8bc"
inactive_tab_edge = "#526994"

[colors.tab_bar.active_tab]
fg_color = "#618bb6"
bg_color = "#e1e1de"
intensity = "Bold"

[colors.tab_bar.inactive_tab]
fg_color = "#858479"
bg_color = "#cbc8bc"

[colors.tab_bar.inactive_tab_hover]
fg_color = "#a85b76"
bg_color = "#e1e1de"

[colors.tab_bar.new_tab]
fg_color = "#858479"
bg_color = "#cbc8bc"

[colors.tab_bar.new_tab_hover]
fg_color = "#a85b76"
bg_color = "#e1e1de"
intensity = "Bold"

[metadata]
name = "kanagawa-paper-canvas"
author = "Simon Ho"
origin_url = "https://github.com/thesimonho/kanagawa-paper.nvim/master/extras/wezterm/kanagawa-paper-canvas.toml"
